name: Pull Request
description: Pull Request 템플릿
title: '[PR] '
labels: ['pull request']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ### 개요

  - type: input
    id: issue_number
    attributes:
      label: 이슈 번호
      description: 해당 PR이 해결하는 이슈의 번호를 기입해주세요.
      placeholder: #123
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: 관련 이슈
      description: 연관된 이슈가 있다면 번호를 기입해주세요.
      placeholder: #456
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 변경 사항

  - type: textarea
    id: changes
    attributes:
      label: 변경 사항
      description: 변경된 내용에 대해 간략히 설명하세요.
      placeholder: |
        - 추가된 기능: 사용자 로그인 기능 추가
        - 삭제된 기능: 오래된 대시보드 기능 삭제
        - 수정된 버그: 로그인 시도 시 에러 메시지가 표시되지 않던 버그 수정
        - 수정된 문서: README.md 업데이트
        - 리팩토링: fetchListings 함수 리팩토링
        - 기타 변경 사항: 패키지 매니저 설정 업데이트
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 구현 세부 사항

  - type: textarea
    id: implementation_details
    attributes:
      label: 구현 세부 사항
      description: 변경 사항에 대한 세부 사항을 작성해주세요.
      placeholder: |
        - 로그인 폼 구현
        - 입력값 유효성 검사
        - 인증 API와의 연동
        - 오류 메시지 표시
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 테스트

  - type: textarea
    id: test_instructions
    attributes:
      label: 테스트 방법
      description: 변경 사항을 테스트하는 방법을 작성해주세요.
      placeholder: |
        - 브라우저에서 로그인 페이지로 이동
        - 잘못된 자격 증명 입력 후 '로그인' 버튼 클릭
        - 오류 메시지 확인
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 참고 자료

  - type: textarea
    id: reference_material
    attributes:
      label: 참고 자료
      description: 관련 문서나 레퍼런스 링크를 추가해주세요.
      placeholder: 참고할 수 있는 자료가 있다면 여기에 추가하세요.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 추가 정보

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보
      description: 추가로 필요한 정보가 있다면 적어주세요.
      placeholder: 기타 필요한 정보가 있다면 여기에 추가하세요.
    validations:
      required: false
