name: 기능 삭제
description: 기존 기능 삭제 요청
title: '[Feature Removal] '
labels: ['enhancement']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ### 기능 설명

  - type: input
    id: feature_name
    attributes:
      label: 삭제할 기능 이름
      description: 삭제할 기능의 이름을 입력하세요.
      placeholder: 오래된 대시보드 기능
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 기능 설명
      description: 삭제할 기능에 대한 설명을 입력하세요.
      placeholder: 오래된 대시보드 기능을 삭제합니다.
    validations:
      required: true

  - type: textarea
    id: feature_reason
    attributes:
      label: 이유
      description: 이 기능을 삭제하는 이유를 설명하세요.
      placeholder: 새로운 대시보드로 대체되었습니다.
    validations:
      required: true

  - type: checkboxes
    id: removal_details
    attributes:
      label: 삭제 세부 사항
      description: 삭제할 항목들을 선택하세요.
      options:
        - label: 관련 컴포넌트 제거
          required: true
        - label: 관련 라우트 삭제
          required: true
        - label: 불필요한 스타일 제거
          required: true

  - type: textarea
    id: reference_material
    attributes:
      label: 참고 자료
      description: 관련 문서나 레퍼런스 링크를 추가해주세요.
      placeholder: 참고할 수 있는 자료가 있다면 여기에 추가하세요.
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보
      description: 추가로 필요한 정보가 있다면 적어주세요.
      placeholder: 기타 필요한 정보가 있다면 여기에 추가하세요.
    validations:
      required: false
